// App-wide constants

export const NAV_ITEMS = ["What's New", "Shop", "Dine", "Services", /* "Stay", */ "Entertain", "Plan your visit", "Visitors Guide"];

export const BRAND_COLOR = '#D19F3B';

export const BREAKPOINTS = {
  xs: 0,
  sm: 600,
  md: 960,
  lg: 1280,
  xl: 1920,
};

// Helper function to get mobile image path for brands
export const getMobileBrandImage = (originalImage: string, brandName?: string, brandSlug?: string): string => {
  // Map of brand slugs to mobile image filenames
  const mobileImageMap: Record<string, string> = {
    'cheezious': '/dine/chezious.jpg',
    'alkaram': '/shops/alkaram-mobile.jpg',
    'almas': '/shops/almas-mobile.jpg',
    'almirah': '/shops/almirah-mobile.jpg',
    'batik-studio': '/shops/batikstudio-mobile.jpg',
    'batikstudio': '/shops/batikstudio-mobile.jpg',
    'bloon': '/shops/bloon-mobile.jpg',
    'bonanza': '/shops/bonanza-mobile.jpg',
    'breakout': '/shops/breakout-mobile.jpg',
    'cambridge': '/shops/cambridge-mobile.jpg',
    'junaid-jamshed': '/shops/junaidjamshed-mobile.jpg',
    'junaidjamshed': '/shops/junaidjamshed-mobile.jpg',
    'kayseria': '/shops/kayseria-mobile.jpg',
    'miniso': '/shops/miniso-mobile.jpg',
    'babys-day-out': '/shops/Babysdayout-mobile.JPG',
    'bata': '/shops/Bata mobile.JPG',
    'brand-city': '/shops/Brand City mobile.JPG',
    'diamond-crown': '/shops/Diamond Crown mobile.JPG',
    'friends-home': '/shops/Friends Home mobile.JPG',
    'haroons': '/shops/Haroons mobile.JPG',
    'jelly-factory': '/shops/Jelly Factory mobile.JPG',
    'johri': '/shops/Johri mobile.JPG',
    'kohinoor-jewels': '/shops/Kohinoor Jewels mobile.JPG',
    'the-linen-company': '/shops/Linen mobile.JPG',
    'little-explorer': '/shops/Little Explorer mobile.JPG',
    'location': '/shops/Location mobile.JPG',
    'majhurat': '/shops/Majhurat mobile.JPG',
    'milli-shoes': '/shops/Milli mobile.JPG',
    'mini-try': '/shops/Mini Try mobile.JPG',
    'mr-kazi': '/shops/Mr Kazi mobile.JPG',
    'ndure':'/shops/Ndure mobile.JPG',
    'readers-point': '/shops/Readers Point mobile.JPG',
    'rivaj': '/shops/Rivaj mobile.JPG',
    'saeed-ghani': '/shops/Saeed Ghani mobile.JPG',
    'service': '/shops/Service mobile.JPG',
    'style-and-comfort': '/shops/Style and Comfort mobile.JPG',
    'sveston': '/shops/Sveston mobile.JPG',
    'tech-studio': '/shops/Tech Studio mobile.JPG',
    'younique': '/shops/Younique mobile.JPG',
    'zero': '/shops/Zero mobile.JPG',
    'just-fragrance': '/shops/Just Fragrance mobile.JPG',
    'gadgets-mobile': '/shops/Gadgets Mobile mobile.JPG',
    'bonanza-satrangi': '/shops/Bonanza Satrangi mobile.JPG',
    'aroma-concepts': '/shops/Aroma Concepts mobile.JPG',
    'eastern-art-and-handicraft': '/shops/Eastern Art and HandiCraft mobile.JPG',
    'taana-baana': '/shops/Taana Baana mobile.JPG',
    'alpha-accessories': '/shops/Alpha Accessories mobile.JPG',
    'ximi-vogue': '/shops/Ximi Vogue mobile.JPG',
    'glamor': '/shops/Glamor mobile.JPG',
    'thai-zone': '/shops/Thai Zone mobile.JPG',
    'tajik': '/shops/Tajik mobile.JPG',
    'sams-abaya': "/shops/Sam's Abaya mobile.JPG",
    'zamin-jewelers': '/shops/Zamin Jewelers mobile.JPG',
    'traditional-khusa': '/shops/Traditional Khusa mobile.JPG',
    'taarkashi': '/shops/Taarkshi mobile.JPG',
    'the-time-zone': '/shops/The Time Zone mobile.JPG',
    'mehran-jewellers': '/shops/Mehran Jewellers mobile.JPG',
    '1st-step': '/shops/1st step mobile.JPG',
    'addidas': '/shops/addidas mobile.JPG',
    'adoro': '/shops/adoro mobile.JPG',
    'anta': '/shops/anta mobile.JPG',
    'apavi': '/shops/apavi mobile.JPG',
    'batik-studio-3': '/shops/batik mobile.JPG',
    'charcoal': '/shops/charcoal mobile.JPG',
    'cinnabon': '/shops/cinnabon mobile.JPG',
    'coppelia': '/shops/coppelia mobile.JPG',
    'couger': '/shops/couger mobile.JPG',
    'crocs': '/shops/crocs mobile.JPG',
    'cross-stitch': '/shops/cross stitch mobile.JPG',
    'dari-mooch': '/shops/dari mooch mobile.JPG',
    'engine': '/shops/engine mobile.JPG',
    'equator': '/shops/equator mobile.JPG',
    'ethnc': '/shops/ethnc mobile.JPG',
    'focus': '/shops/focus mobile.JPG',
    'fpl': '/shops/fpl mobile.fplJPG',
    'goshes': '/shops/Goshes mobile.JPG',
    'gulzari': '/shops/gulzari mobile.JPG',
    'haseen-jewelers': '/shops/haseen jewelers mobile.JPG',
    'hopscotch': '/shops/hopscotch mobile.JPG',
    'hub': '/shops/hub mobile.JPG',
    'hunza-emporium': '/shops/hunza emporium mobile.JPG',
    'hush-puppies': '/shops/hush puppies mobile.JPG',
    'insignia': '/shops/insignia mobile.JPG',
    'j.-fragrance-and-costmetics': '/shops/J-fragrance and costmetics mobile.JPG',
    'jaffer-nees': '/shops/jafferjess mobile.JPG',
    'jc-buckman': '/shops/jc buckman mobile.JPG',
    'juice-fruity': '/shops/juice fruity mobile.JPG',
    'julke': '/shops/julke mobile.JPG',
    'kef-diamonds': '/shops/kef diamonds mobile.JPG',
    'khadi': '/shops/khadi mobile.JPG',
    'khusa-factory': '/shops/khusa factory mobile.JPG',
    'king-corn': '/shops/king corn mobile.JPG',
    'lady-privacy': '/shops/lady privacy mobile.JPG',
    'limelite': '/shops/limelite mobile.JPG',
    'lullusar': '/shops/lullusar mobile.JPG',
    'maria-b-2': '/shops/maria b 2 mobile.JPG',
    'maria-b-3': '/shops/maria b 3 mobile.JPG',
    'maybelline': '/shops/maybelline mobile.JPG',
    'miracle': '/shops/miracle mobile.JPG',
    'mocciani': '/shops/mocciani mobile.JPG',
    'monark': '/shops/monark mobile.JPG',
    'mtj-fragrance': '/shops/mtj fragrance mobile.JPG',
    'nizam-watch-house': '/shops/nizam watch house mobile.JPG',
    'pop-nosh': '/shops/pop nosh mobile.JPG',
    // 'rivaj': '',
    'royal-tag': '/shops/royal tag mobile.JPG',
    'sapphire': '/shops/sapphire mobile.JPG',
    'saya': '/shops/saya mobile.JPG',
    'scents-and-stories': '/shops/scents and stories mobile.JPG',
    'sketcher': '/shops/sketchers mobile.JPG',
    'sona-chandi': '/shops/sona chandi mobile.JPG',
    'speed-sports': '/shops/speed sports mobile.JPG',
    'style-in-shoes': '/shops/style in shoes mobile.JPG',
    'svesto': '/shops/svesto mobile.JPG',
    'swarovski': '/shops/swarovski mobile.JPG',
    'syed-royal-optics': '/shops/syed royal optics mobile.JPG',
    'tagheuer': '/shops/tagheuer mobile.JPG',
    'tayyab-jewelers': '/shops/tayyab jewelers mobile.JPG',
    'tessoro': '/shops/tessoro mobile.JPG',
    'the-body-shop': '/shops/the body shop mobile.JPG',
    'tim-hortins': '/shops/tim hortins mobile.JPG',
    'ultra-club': '/shops/ultra club mobile.JPG',
    'wasim-badami-by-hemani': '/shops/wasim badami by hemani mobile.JPG',
    'derma-orchid': '/Services/derma orchid mobile.JPG',
    'dermaorchid': '/Services/derma orchid mobile.JPG',
    'derma orchid': '/Services/derma orchid mobile.JPG',
    'aesthetics-and-dental-works': '/Services/aesthetic n dental work mobile.JPG',
    'aestheticsanddentalworks': '/Services/aesthetic n dental work mobile.JPG',
    'aesthetics and dental works': '/Services/aesthetic n dental work mobile.JPG',
    'aesthetic-n-dental-work': '/Services/aesthetic n dental work mobile.JPG',
    'aestheticndentalwork': '/Services/aesthetic n dental work mobile.JPG',
    'aesthetic n dental work': '/Services/aesthetic n dental work mobile.JPG',
    'imc': '/Services/imc mobile.JPG',
    'imc-integrative-medical-center': '/Services/imc mobile.JPG',
    'integrative-medical-center': '/Services/imc mobile.JPG',
    'pakistan-currency-exchange': '/Services/pakistan currency exchange mobile.JPG',
    'pakistancurrencyexchange': '/Services/pakistan currency exchange mobile.JPG',
    'pakistan currency exchange': '/Services/pakistan currency exchange mobile.JPG',
    'currency-exchange': '/Services/pakistan currency exchange mobile.JPG',
    // 'zero': '',
    'corn-station': '/shops/corn station mobile.JPG',
    'f-optical-and-watch': '/shops/f optical and watch mobile.JPG',
    'foot-and-leather': '/shops/foot and leather mobile.JPG',
    'h-n-h-decor': '/shops/h n h decor mobile.JPG',
    // 'imc': '/shops/imc mobile.JPG',
    'kapok': '/shops/kapok mobile.JPG',
    'king-coffee': '/shops/king coffee mobile.JPG',
    'melon-box': '/shops/melon box mobile.JPG',
    'mi': '/shops/mi mobile.JPG',
    'mr-game': '/shops/mr game mobile.JPG',
    'pound-store': '/shops/pound store mobile.JPG',
    'rohi-reet': '/shops/rohi reet mobile.JPG',
    'silver-stition': '/shops/silverstition mobile.JPG',
    'sport-snation': '/shops/sport snation mobile.JPG',
    'sweet-and-salt': '/shops/sweet and salt mobile.JPG',
    'abc-fragrance': '/shops/abc fragrance mobile.JPG',
    // 'alkaram': '',
    // 'almas': '',
    'amd': '/shops/amd mobile.JPG',
    'amir': '/shops/amir mobile.JPG',
    'bareeze': '/shops/bareeze mobile.JPG',
    'batik': '/shops/batik mobile.JPG',
    'beech-tree': '/shops/beach tree mobile.JPG',
    'bonanza-satrangi-beauty': '/shops/bonanza satrangi beauty mobile.JPG',
    'borjan': '/shops/borjan mobile.JPG',
    'brackets': '/shops/brackets mobile.JPG',
    // 'cambridge': '',
    'charizma': '/shops/charizma mobile.JPG',
    'chinyere': '/shops/chinyere mobile.JPG',
    'chunri': '/shops/chunri by jalips mobile.JPG',
    'corio': '/shops/corio mobile.JPG',
    'dinners': '/shops/dinners mobile.JPG',
    'dynasty': '/shops/dynasty mobile.JPG',
    'ecs': '/shops/eccs mobile.JPG',
    'edenrobe': '/shops/edenrobe mobile.JPG',
    'elegant': '/shops/elegant mobile.JPG',
    'excel': '/shops/excel mobile.JPG',
    'furor': '/shops/furor mobile.JPG',
    'generation': '/shops/generation mobile.JPG',
    'hi-volts': '/shops/hi volts mobile.JPG',
    'ideas': '/shops/ideas mobile.JPG',
    'jiyas-creation': '/shops/jiyas mobile.JPG',
    // 'junaid-jamshed': '',
    // 'kayseria': '',
    'lawrance': '/shops/lawrance mobile.JPG',
    'little-people': '/shops/little people mobile.JPG',
    'logo': '/shops/logo mobile.JPG',
    'm-basic': '/shops/m basic mobile.JPG',
    'maria-b': '/shops/maria b 2 mobile.JPG',
    'minnie-mirrors': '/shops/minnie mirros mobile.JPG',
    'mona': '/shops/mona mobile.JPG',
    'nakoosh': '/shops/nakoosh mobile.JPG',
    'nishat': '/shops/nishat-mobile.JPG',
    'oaks': '/shops/oaks mobile.JPG',
    'one': '/shops/one mobile.JPG',
    'out-fitters': '/shops/outfitters mobile.JPG',
    'revolution-london': '/shops/revolution london mobile.JPG',
    'rth': '/shops/rth mobile.JPG',
    'sana-safinaz': '/shops/sana safinaz mobile.JPG',
    'siraj-sons-silver-shop': '/shops/siraj sones silver shop mobile.JPG',
    'sohaya': '/shops/sohaye mobile.JPG',
    'sowearg': '/shops/sowearg mobile.JPG',
    'stylo': '/shops/stylo mobile.JPG',
    'swiss-arabia': '/shops/swiss arabia mobile.JPG',
    'threads-and-motys': '/shops/threads and motys mobile.JPG',
    'tiny-years': '/shops/tiny years mobile.JPG',
    'toy-club': '/shops/toy club mobile.JPG',
    'umaiza': '/shops/umaiza mobile.JPG',
    'uniworth': '/shops/uniworth mobile.JPG',
    'unze': '/shops/unze mobile.JPG',
    'vereity-bags-and-costmetics': '/shops/vereity bags and costmetics mobile.JPG',
    'zeen': '/shops/zeen mobile.JPG',
    'zubaidas': '/shops/zubaidas mobile.JPG',
    
    '361':'/shops/361 mobile.JPG',
    'a-and-i': '/shops/a and i mobile.JPG',
    'ali-baba': '/shops/alibaba mobile.JPG',
    'anamta-fateh': '/shops/anamta fateh mobile.JPG',
    'anaya-jewelery': '/shops/anaya jewelery mobile.JPG',
    'apavi-shoes': '/shops/apavi shoes mobile.JPG',
    'bling-collection': '/shops/bling collection mobile.JPG',
    'minime-kids-mobile': '/shops/minime kids mobile.JPG',
    'dare-to-dazzle': '/shops/dare to dazzle mobile.JPG',
    'designer-vault': '/shops/designer vault mobile.JPG',
    'designervault': '/shops/designer vault mobile.JPG',
    'designer vault': '/shops/designer vault mobile.JPG',
    'dollar-house': '/shops/dollar house mobile.JPG',
    'dollarhouse': '/shops/dollar house mobile.JPG',
    'dollar house': '/shops/dollar house mobile.JPG',
    'dollar-world': '/shops/dollar world mobile.JPG',
    'dollarworld': '/shops/dollar world mobile.JPG',
    'dollar world': '/shops/dollar world mobile.JPG',
    'good-life': '/shops/good life mobile.JPG',
    'goodlife': '/shops/good life mobile.JPG',
    'good life': '/shops/good life mobile.JPG',
    'irhas-kids': '/shops/irhas kids mobile.JPG',
    'irhaskids': '/shops/irhas kids mobile.JPG',
    'irhas kids': '/shops/irhas kids mobile.JPG',
    'jockey': '/shops/jockey mobile.JPG',
    'just-for-men': '/shops/just for men mobile.JPG',
    'justformen': '/shops/just for men mobile.JPG',
    'just for men': '/shops/just for men mobile.JPG',
    'kundan': '/shops/kundan mobile.JPG',
    'leisure-club': '/shops/leisure club mobile.JPG',
    'leisureclub': '/shops/leisure club mobile.JPG',
    'leisure club': '/shops/leisure club mobile.JPG',
    'mipj-store': '/shops/mip.j mobile.JPG',
    'mip.j': '/shops/mip.j mobile.JPG',
    'mipj': '/shops/mip.j mobile.JPG',
    'mip j': '/shops/mip.j mobile.JPG',
    'miral': '/shops/miral mobile.JPG',
    'miraal': '/shops/miral mobile.JPG',
    'north-face': '/shops/north face mobile.JPG',
    'northface': '/shops/north face mobile.JPG',
    'north face': '/shops/north face mobile.JPG',
    'the north face': '/shops/north face mobile.JPG',
    'originals-of-london': '/shops/original mobile.JPG',
    'originalsoflondon': '/shops/original mobile.JPG',
    'originals of london': '/shops/original mobile.JPG',
    'original': '/shops/original mobile.JPG',
    'qumas': '/shops/qumas mobile.JPG',
    'roll-over': '/shops/roll over mobile.JPG',
    'rollover': '/shops/roll over mobile.JPG',
    'roll over': '/shops/roll over mobile.JPG',
    'scents-and-secrets': '/shops/scents and secrets mobile.JPG',
    'scentsandsecrets': '/shops/scents and secrets mobile.JPG',
    'scents and secrets': '/shops/scents and secrets mobile.JPG',
    'tiny-tots': '/shops/tiny tots mobile.JPG',
    'tinytots': '/shops/tiny tots mobile.JPG',
    'tiny tots': '/shops/tiny tots mobile.JPG',
    'time-space-collection': '/shops/time and space mobile.JPG',
    'timeandspacecollection': '/shops/time and space mobile.JPG',
    'time and space collection': '/shops/time and space mobile.JPG',
    'time & space collection': '/shops/time and space mobile.JPG',
    'time and space': '/shops/time and space mobile.JPG',
    'time & space': '/shops/time and space mobile.JPG',
    'toy-land': '/shops/toy land mobile.JPG',
    'toyland': '/shops/toy land mobile.JPG',
    'toy land': '/shops/toy land mobile.JPG',
    'zebaish': '/shops/zebaish mobile.JPG'

  };

  // Try to find mobile image by slug first (most reliable)
  if (brandSlug) {
    const normalizedSlug = brandSlug.toLowerCase().trim();
    if (mobileImageMap[normalizedSlug]) {
      return mobileImageMap[normalizedSlug];
    }
  }

  // Try to find mobile image by brand name
  if (brandName) {
    const normalizedName = brandName.toLowerCase().replace(/\s+/g, '-');
    if (mobileImageMap[normalizedName]) {
      return mobileImageMap[normalizedName];
    }
  }

  // Try to extract brand name from image path
  const imageName = originalImage.split('/').pop()?.toLowerCase() || '';
  const brandKey = imageName
    .replace(/\.(jpg|jpeg|png|webp)$/, '')
    .replace(/\s+/g, '-')
    .replace(/-logo$/, '');

  if (mobileImageMap[brandKey]) {
    return mobileImageMap[brandKey];
  }

  // If no mobile image found, return original
  return originalImage;
};

// Helper function to get mobile image path for dine/restaurants
export const getMobileDineImage = (originalImage: string, dineName?: string, dineSlug?: string): string => {
  // Map of dine slugs/names to mobile image filenames
  const mobileDineImageMap: Record<string, string> = {
    'mcdonalds': '/dine/macdonald-mobile.jpg',
    'mcdonald\'s': '/dine/macdonald-mobile.jpg',
    'macdonald': '/dine/macdonald-mobile.jpg',
    'hardees': '/dine/hardees-mobile.jpg',
    'hardee\'s': '/dine/hardees-mobile.jpg',
    'pizzahut': '/dine/pizzahut-mobile.jpg',
    'pizza-hut': '/dine/pizzahut-mobile.jpg',
    'pizza hut': '/dine/pizzahut-mobile.jpg',
    'wild-wings': '/dine/wildwings-mobile.jpg',
    'wildwings': '/dine/wildwings-mobile.jpg',
    'wild wings': '/dine/wildwings-mobile.jpg',
    'cheezious': '/dine/cheezious mobile view.jpg',
    'starbucks': '/starbucks-mobile.jpg',
    'nandos': '/nandos-mobile.jpg',
    'nando\'s': '/nandos-mobile.jpg',
    'eataly': '/eataly-mobile.jpg',
    'angelina': '/angelina-mobile.jpg',
    'social-house': '/socialhouse-mobile.jpg',
    'socialhouse': '/socialhouse-mobile.jpg',
    'cheesecake-factory': '/cheesecakefactory-mobile.jpg',
    'cheesecakefactory': '/cheesecakefactory-mobile.jpg',
    'markette': '/markette-mobile.jpg',
    'pizza-express': '/pizzaexpress-mobile.jpg',
    'pizzaexpress': '/pizzaexpress-mobile.jpg',
    'shake-shack': '/shakeshack-mobile.jpg',
    'shakeshack': '/shakeshack-mobile.jpg',
    'tim-hortons': '/dine/tim horton mobile.JPG',
    'timhortons': '/dine/tim horton mobile.JPG',
    'tim hortons': '/dine/tim horton mobile.JPG',
    'tim-horton': '/dine/tim horton mobile.JPG',
    'timhorton': '/dine/tim horton mobile.JPG',
    'cinnabon': '/cinnabon-mobile.jpg',
    'baskin-robbins': '/dine/baskin robin mobile.JPG',
    'baskinrobbins': '/dine/baskin robin mobile.JPG',
    'baskin robins': '/dine/baskin robin mobile.JPG',
    'baskin robin': '/dine/baskin robin mobile.JPG',
    'cold-stone-creamery': '/coldstonecreamery-mobile.jpg',
    'coldstonecreamery': '/coldstonecreamery-mobile.jpg',
    'dunkin': '/dunkin-mobile.jpg',
    'kfc': '/kfc-mobile.jpg',
    'subway': '/subway-mobile.jpg',
    'burger-king': '/burgerking-mobile.jpg',
    'burgerking': '/burgerking-mobile.jpg',
    'papa-johns': '/papajohns-mobile.jpg',
    'papajohns': '/papajohns-mobile.jpg',
    'dominos-pizza': '/dominospizza-mobile.jpg',
    'dominospizza': '/dominospizza-mobile.jpg',
    'costa-coffee': '/costacoffee-mobile.jpg',
    'costacoffee': '/costacoffee-mobile.jpg',
    'gloria-jeans-coffees': '/dine/gloria mobile.JPG',
    'gloriajeanscoffees': '/dine/gloria mobile.JPG',
    'redapple': '/dine/redapple-mobile.JPG',
    'red-apple': '/dine/redapple-mobile.JPG',
    'optp': '/dine/optp-mobile.JPG',
    'chachajee': '/dine/chachajee-mobile.JPG',
    'simplysufi': '/dine/simplesufi-mobile.JPG',
    'simply-sufi': '/dine/simplesufi-mobile.JPG',
    'rewayat': '/dine/rewayat-mobile.JPG',
    'spicefactory': '/dine/spicefactory-mobile.JPG',
    'spice-factory': '/dine/spicefactory-mobile.JPG',
    'chinagrill': '/dine/chinagrill-mobile.JPG',
    'china-grill': '/dine/chinagrill-mobile.JPG',
    'kababjees': '/dine/kababjees-mobile.JPG',
    'kabab-jees': '/dine/kababjees-mobile.JPG',
    'coffee-planet': '/dine/coffee planet mobile.JPG',
    'coffeeplanet': '/dine/coffee planet mobile.JPG',
    'coffee planet': '/dine/coffee planet mobile.JPG',
    'corn-station': '/dine/corn station mobile.JPG',
    'cornstation': '/dine/corn station mobile.JPG',
    'corn station': '/dine/corn station mobile.JPG',
    'asian-fusion': '/dine/asian fusion mobile.JPG',
    'asianfusion': '/dine/asian fusion mobile.JPG',
    'asian fusion': '/dine/asian fusion mobile.JPG',
    'eklairs': '/dine/eklairs mobile.JPG',
    'frutastic': '/dine/frutastic mobile.JPG',
    'gloria jeans coffees': '/dine/gloria mobile.JPG',
    'gloria': '/dine/gloria mobile.JPG',
    'goshez': '/dine/goshez mobile.JPG',
    'islamic-honey-centre': '/dine/islamic honey mobile.JPG',
    'islamichoneycentre': '/dine/islamic honey mobile.JPG',
    'islamic honey centre': '/dine/islamic honey mobile.JPG',
    'islamic honey': '/dine/islamic honey mobile.JPG',
    'juice-fruity': '/dine/juice fruity mobile.JPG',
    'juicefruity': '/dine/juice fruity mobile.JPG',
    'juice fruity': '/dine/juice fruity mobile.JPG',
    'juice-station': '/dine/juice station mobile.JPG',
    'juicestation': '/dine/juice station mobile.JPG',
    'juice station': '/dine/juice station mobile.JPG',
    'king-coffee': '/dine/king coffee mobile.JPG',
    'kingcoffee': '/dine/king coffee mobile.JPG',
    'king coffee': '/dine/king coffee mobile.JPG',
    'king-corn': '/dine/king corn mobile.JPG',
    'kingcorn': '/dine/king corn mobile.JPG',
    'king corn': '/dine/king corn mobile.JPG',
    'pop-nosh': '/dine/popnosh mobile.JPG',
    'popnosh': '/dine/popnosh mobile.JPG',
    'pop nosh': '/dine/popnosh mobile.JPG',
    'sweet-salt': '/dine/sweet&salt mobile.JPG',
    'sweetandsalt': '/dine/sweet&salt mobile.JPG',
    'sweet & salt': '/dine/sweet&salt mobile.JPG',
    'ashraf-naturals': '/dine/ashraf naturals mobile.JPG',
    'ashrafnaturals': '/dine/ashraf naturals mobile.JPG',
    'ashraf naturals': '/dine/ashraf naturals mobile.JPG',
    'dark-side': '/dine/dark side mobile.JPG',
    'darkside': '/dine/dark side mobile.JPG',
    'dark side': '/dine/dark side mobile.JPG',
    'cigarettes-chocolates': '/dine/ciggeretes and choclates mobile.JPG',
    'cigaretteschocolates': '/dine/ciggeretes and choclates mobile.JPG',
    'cigarettes & chocolates': '/dine/ciggeretes and choclates mobile.JPG',
    'cigarettes-and-chocolates': '/dine/ciggeretes and choclates mobile.JPG',
    'house-of-mandi': '/dine/house of mandi mobile.JPG',
    'houseofmandi': '/dine/house of mandi mobile.JPG',
    'house of mandi': '/dine/house of mandi mobile.JPG',
    'howdy': '/dine/howdy mobile.JPG',
    'ice-curl': '/dine/ice curl mobile.JPG',
    'icecurl': '/dine/ice curl mobile.JPG',
    'ice curl': '/dine/ice curl mobile.JPG',
    'jelly-factory': '/dine/Jelly Factory mobile.JPG',
    'jellyfactory': '/dine/Jelly Factory mobile.JPG',
    'jelly factory': '/dine/Jelly Factory mobile.JPG',
    'jojo': '/dine/jojo mobile.JPG',
    'juices-land': '/dine/juices land mobile.JPG',
    'juicesland': '/dine/juices land mobile.JPG',
    'juices land': '/dine/juices land mobile.JPG',
    'pepes-piri-piri': '/dine/pepes piri mobile.JPG',
    'pepespiripiri': '/dine/pepes piri mobile.JPG',
    'pepes piri piri': '/dine/pepes piri mobile.JPG',
    'pepes piri': '/dine/pepes piri mobile.JPG',
    'pita': '/dine/pita mobile.JPG',
    'pizza-n-pasta': '/dine/pizza n pasta mobile.JPG',
    'pizzanpasta': '/dine/pizza n pasta mobile.JPG',
    'pizza n pasta': '/dine/pizza n pasta mobile.JPG',
    'potato-factory': '/dine/potato factory mobile.JPG',
    'potatofactory': '/dine/potato factory mobile.JPG',
    'potato factory': '/dine/potato factory mobile.JPG',
    'the potato factory': '/dine/potato factory mobile.JPG',
    'sip-smart': '/shops/sip smart mobile.JPG',
    'sipsmart': '/shops/sip smart mobile.JPG',
    'sip smart': '/shops/sip smart mobile.JPG',
    'sips smart': '/shops/sip smart mobile.JPG',
    'sohaibs-wood-cocoa': '/shops/sohaibs mobile.JPG',
    'sohaibswoodcocoa': '/shops/sohaibs mobile.JPG',
    'sohaibs wood cocoa': '/shops/sohaibs mobile.JPG',
    'sohaibs': '/shops/sohaibs mobile.JPG',
    'sohaib\'s wood & cocoa': '/shops/sohaibs mobile.JPG',
    'tawa-chatkhara': '/dine/tawa chatkhara mobile.JPG',
    'tawachatkhara': '/dine/tawa chatkhara mobile.JPG',
    'tawa chatkhara': '/dine/tawa chatkhara mobile.JPG',
    'tayto': '/dine/tayto mobile.JPG',
    'turk-station': '/dine/turk mobile.JPG',
    'turkstation': '/dine/turk mobile.JPG',
    'turk station': '/dine/turk mobile.JPG',
    'true-taste': '/dine/true taste mobile.JPG',
    'truetaste': '/dine/true taste mobile.JPG',
    'true taste': '/dine/true taste mobile.JPG',
  };

  // Try to find mobile image by slug first (most reliable)
  if (dineSlug) {
    const normalizedSlug = dineSlug.toLowerCase().trim();
    if (mobileDineImageMap[normalizedSlug]) {
      return mobileDineImageMap[normalizedSlug];
    }
  }

  // Try to find mobile image by dine name
  if (dineName) {
    const normalizedName = dineName.toLowerCase().replace(/\s+/g, '-').replace(/'/g, '').replace(/&/g, 'and');
    if (mobileDineImageMap[normalizedName]) {
      return mobileDineImageMap[normalizedName];
    }
    // Also try with original spaces and apostrophes
    const nameWithSpaces = dineName.toLowerCase();
    if (mobileDineImageMap[nameWithSpaces]) {
      return mobileDineImageMap[nameWithSpaces];
    }
  }

  // Try to extract dine name from image path and construct mobile image path
  const imageName = originalImage.split('/').pop()?.toLowerCase() || '';
  const dineKey = imageName
    .replace(/\.(jpg|jpeg|png|webp)$/, '')
    .replace(/\s+/g, '-')
    .replace(/-logo$/, '');

  if (mobileDineImageMap[dineKey]) {
    return mobileDineImageMap[dineKey];
  }

  // Try to construct mobile image path from original image name
  // If original is '/pizzahut.jpeg', try '/pizzahut-mobile.jpg'
  const baseName = imageName.replace(/\.(jpg|jpeg|png|webp)$/, '');
  
  // Check if this matches any known pattern (we can't check file existence in browser, but we can try common patterns)
  const commonPatterns = [
    baseName.replace(/\s+/g, '').toLowerCase() + '-mobile.jpg',
    baseName.replace(/\s+/g, '-').toLowerCase() + '-mobile.jpg',
    baseName.replace(/-/g, '').toLowerCase() + '-mobile.jpg',
  ];
  
  for (const pattern of commonPatterns) {
    const testKey = pattern.replace('-mobile.jpg', '').replace('.jpg', '');
    if (mobileDineImageMap[testKey]) {
      return mobileDineImageMap[testKey];
    }
  }

  // If no mobile image found, return original
  return originalImage;
};

